package com.paypal.location.config;

import com.paypal.location.config.app.ApplicationConfig;
import com.paypal.location.config.app.ManagedEnvironmentType;
import com.paypal.location.exceptions.ApplicationConfigException;
import com.paypal.location.exceptions.ExceptionCode;
import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.NoSuchElementException;

/**
 * User: pderoxas
 * Date: 9/30/13
 * Time: 4:42 PM
 * Helper methods associated to the application configuration classes generated by jaxb
 */
public class ApplicationConfigHelper {
    private Logger logger = Logger.getLogger(this.getClass());

    @Autowired
    private ApplicationConfig applicationConfig;

    public ManagedEnvironmentType getManagedEnvironment(final String environmentId) throws ApplicationConfigException {

        try {
            //find the matching environment configuration in application.xml
            return Iterables.find(applicationConfig.getManagedEnvironment(), new Predicate<ManagedEnvironmentType>() {
                public boolean apply(ManagedEnvironmentType arg) {
                    return arg.getId().equals(environmentId);
                }
            });
        }
        catch (NoSuchElementException ex) {
            logger.error(ex.getMessage(), ex);
            throw new ApplicationConfigException("Environment (" + environmentId + ") is not configured in application.xml.", ExceptionCode.APPLICATION_CONFIG_EXCEPTION, ex);
        }
    }
}
